### PR TITLE
Treat web/js and web/css requirements as web/bundles

### PR DESCRIPTION
**Pull request by GuGuss**
I guess that the writable requirements should be consistent between the following folders: `web/bundles`, `web/css` and `web/js`.

If not, there we are asking the complete `web` folder to be writable which doesn't make sense IMHO.

### CODE REVIEW

**Comment by mbessolov** [comment]
There are three types of directories in _web_ directory:
* pre-existing, they come with the source code, e.g. _web/media_ and _web/uploads_
* created by `composer install`, e.g. _web/bundles_
* created by the console application installer (`app/console oro:install`) or the web application installer  - these are _web/js_ and _web/css_

The proposed change modifies the requirements verification in the way that _web/css_ and _web/js_ must be writable *and must exist* before the installer creates them. And for the installer to be able to create these directories, the entire _web_ directory must be writable.

This PR cannot be accepted as is. A possible solution would be to add _web/css_ and _web/js_ directories to the source code along with the proposed change to app/OroRequirements.php

**Comment by GuGuss** [comment]
Hi, I completely agree with you. 

The only thing that I don't think is right, is to require the entire web directory to be writable simply to create `web/js` and `web/css` because they're not there.

I've added a commit to add them to the application source code and remove them from '.gitignore'.

What do you think?

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by GuGuss** [comment]
Just signed the CLA  :+1:

**Comment by mbessolov** [comment]
Thank you @GuGuss, we'll review and merge this PR before the next release.

**Comment by napoleon2121** [comment]
any possibility to make the install at plesk ? ?  (sorry for writing in here but i cannot make a new post)

**Comment by manowark** [comment]
Not actual for latest releases.

**Pull request closed without merging**
